#!/bin/bash


check=`df -hT|grep /opt/omni/bin/drim/tmp|awk {'print '$6'}`
if [ $check="/opt/omni/bin/drim/tmp" ]
 then
  df -hT /opt/omni/bin/drim/tmp
 else
  echo "maintanace is needed"
fi
#test utre
check=`cat /etc/fstab | grep /opt/omni |awk {'print $2'}`

if [ $check="/opt/omni/bin/drim/tmp" ]
 then
  echo "good"
 else
  vgs && df -h /
fi
