#!/bin/bash
#created by joro
#BASF data-protector created
#for HPSA only

check=`df -hT|grep /opt/omni/bin/drim/tmp|awk {'print '$6'}`

if [ $check == "/opt/omni/bin/drim/tmp" ]
 then
  df -hT /opt/omni/bin/drim/tmp
 else
  echo "maintanace is needed"
fi
